name: .NET Core Desktop

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: BackendApi.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
